/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/Zachareee/savesync_gdrive */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 10 "main.go"

#include <stdlib.h>

struct Info {
	char *name;
	char *description;
	char *author;
	char *icon_url;
};

struct FileDetails {
	char *filename;
	unsigned long long dateModified;
};

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) struct Info info(void);

/* Return type for validate */
struct validate_return {
	char* r0;
	char* r1;
};
extern __declspec(dllexport) struct validate_return validate(char* credentials, char* redirect_uri);

/* Return type for extract_credentials */
struct extract_credentials_return {
	char* r0;
	char* r1;
};
extern __declspec(dllexport) struct extract_credentials_return extract_credentials(char* uri);

/* Return type for read_cloud */
struct read_cloud_return {
	GoUint64 r0;
	struct FileDetails* r1;
	char* r2;
};
extern __declspec(dllexport) struct read_cloud_return read_cloud(char* accessToken);
extern __declspec(dllexport) char* upload(char* access_token, char* filename, GoUint64 date_modified, char* data, GoUint64 data_length);

/* Return type for download */
struct download_return {
	void* r0;
	GoUint64 r1;
	char* r2;
};
extern __declspec(dllexport) struct download_return download(char* accessToken, char* filename);
extern __declspec(dllexport) void free_memory(char* str);
extern __declspec(dllexport) void close_dll(void);

#ifdef __cplusplus
}
#endif
